'use strict';var f=!0,l=null,m=!1;function w(){return function(){}}function y(g){return function(){return this[g]}}
(function(g,r){function W(){function v(){}function G(a,b){this.width=a;this.height=b}function H(a,b){this.x=a;this.y=b}function Z(){}function N(){this.Gb={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",
crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",
forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",honeydew:"#f0fff0",hotpink:"#ff69b4","indianred ":"#cd5c5c","indigo ":"#4b0082",ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgrey:"#d3d3d3",lightgreen:"#90ee90",lightpink:"#ffb6c1",
lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370d8",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",
moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#d87093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",
seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"}}function I(){function a(){function a(c){var p={},k=d[c].prototype,g;for(g in k){var h=k[g];if("function"===typeof h){if(h===b[g]){for(var q=
m,n=c+1;n<d.length;++n)if(d[n].prototype[g]!==h){q=f;break}if(!q){q=m;for(n=c-1;0<=n;--n){var r=d[n].prototype[g];if(r!==h&&"undefined"!==typeof r){h=function(a,c){return function(){return e[a][c].apply(b,arguments)}}(n,g);q=f;break}}if(!q)continue}}q={};for(n=c-1;0<=n;--n)if(d[n].prototype[g]!==h){q=e[n];break}p[g]=function(a,c,d,e){return function(){var a=b.ea;b.ea=e;var T={},p;for(p in d){var k=d[p];"function"===typeof k&&(T[p]=b[p],b[p]=k)}p=c.apply(b,arguments);for(var g in T)b[g]=T[g];b.ea=
a;return p}}(g,h,k,q)}}e.push(p)}for(var d=b.constructor.ancestors,e=[],p=0;p<d.length;++p)a(p);b.ea=0<e.length?e[e.length-1]:{}}var b=this;this.ea=l;Object.defineProperty(this,"base",{get:function(){b.ea||a();return b.ea},set:function(){e.l("base is read-only")},B:m});this.construct.apply(this,arguments)}function V(a){e.d(0<a.length,"Composite objects must not be empty");var b=a[0],c=this,d;for(d in b)try{"function"===typeof b[d]&&(c[d]=function(a,b){return function(){for(var d,e=0;e<b.length;++e)d=
b[e],d=d[a].apply(d,arguments);return d==b[b.length-1]?c:d}}(d,a))}catch(T){}}function x(a,b,c,d,T,p){e.d(b==B.ThreeJs,"Only ThreeJs is supported");this.ec=a;this.i=b;this.e=c;this.ic=d;this.za=T;this.Fb=p;this.q=[]}function L(a){this.L=a}function O(){e.n("Creating Cache Factory");this.L={}}function X(){this.la=m;this.ub=this.gb=0;this.t=r.createElement("div");this.t.style.position="fixed";this.t.style.zIndex=999999999;this.t.style.left="0px";this.t.style.top="0px";this.t.style.backgroundColor="black";
this.t.style.color="lime";this.t.style.fontStyle="bold";this.t.style.fontSize="200%";this.t.style.fontFamily="sans-serif";this.t.display="none";var a=this;this.Ec=setInterval(function(){a.hb=a.gb;a.Yc=a.ub;a.gb=0;a.ub=0},1E3)}function M(){}function z(){}function W(){}function C(){}function Y(a){this.Ha=a;this.Lc=0;this.Da={};this.Ma=this.Na=this.Pa=this.Oa=Number.MIN_VALUE;this.p()}function $(){e.n("Creating Tracker");this.xa={};this.Mc=this.Nc=0;this.Ab={}}function P(){this.Z={}}function Q(a,b,c,
d){this.A=a;this.ba=b;this.Za="undefined"===typeof d?-1:d;this.f=c;this.u=a.model}function U(){}function ca(){}function da(){}function D(a){this.a=a;this.Sb();this.a.ua.wb(new H(0,0));this.qc();var b=this;this.a.on("removemodel",function(a){b.m&&a.model===b.m.u&&(b.m=l);if(b.U)for(var d=0;3>d;++d){var e=b.U[d];e&&a.model===e.u&&(b.U[d]=l)}if(b.$)for(d=0;3>d;++d)(e=b.$[d])&&a.model===e.u&&(b.$[d]=l)})}function u(a,b,c,d){e.n("Creating ThreeJs Camera");this.e=new THREE.Camera;this.ib=new THREE.Frustum;
this.Ea=a;this.Ia=b;this.F=c;this.I=d;this.Kc();this.Bc()}function J(a){e.d("undefined"!==typeof a,"Engine must be defined.");e.d("undefined"!==typeof a.i,"Renderer must be defined.");this.a=a;this.i=a.i;this.gc=new THREE.Projector}function A(a,b){this.j=a;this.A=b;this.S=g.voodoo.engine.S;this.wa=l;this.f=new THREE.Object3D;this.j.add(this.f);this.ra=[];this.ja=[];this.h=new P;Object.defineProperty(this,"objects",{get:function(){for(var a=[],b=this.f.children,e=0;e<b.length;++e)b[e].addedToVoodooScene&&
a.push(b[e]);return a},set:function(){e.l("objects is read-only")},B:m})}function E(){e.n("Creating ThreeJs Scene Factory");this.j=new THREE.Scene}function R(a,b,c){e.d(a,"Triggers must be valid");e.d(b,"Scene must be valid");e.d(c,"View must be valid");this.v=a;this.j=b;this.A=c}function K(){e.n("Creating ThreeJs Triggers Factory");this.v=[]}function s(a){this.a=a;this.aa=[];this.pd();this.zc();this.Ac();this.Tc();this.oa=new X;this.$b=new Date;this.fc=m}function t(a){a=new q(a);e.d(a.renderer==
B.ThreeJs,"Only ThreeJs is supported");e.n("Creating Engine");e.n("   version: 0.8.8");e.n("   userAgent: "+navigator.userAgent);for(var b in a)e.n("   options."+b+": "+a[b]);g.WebGLRenderingContext||e.l("WebGL not supported");this.c=a;this.qd();this.jb=new O;this.S=new $;this.Q=[];Object.defineProperty(this,"models",{get:function(){for(var a=[],b=0;b<this.Q.length;++b)a.push(this.Q[b]);return a},set:function(){e.l("models is read-only")},B:m});this.fd();switch(a.renderer){case B.ThreeJs:this.i=new s(this);
this.ua=new J(this);break;default:this.ua=this.i=l,e.l("Unsupported renderer")}this.h=new P;this.Qa=new D(this);g.voodoo.engine=this;a.standardLighting&&(e.n("Creating standard lights"),new ea({color:"white"}),new aa({color:"white"}));this.Ta=this.Ua=this.$a=-1;b=0===this.c.updateInterval;var c=0===this.c.renderInterval;if(a.frameLoop){e.n("Beginning frame loop");(b||c)&&this.hc(b,c);var d=this;b||(this.$a=g.setInterval(function(){d.p()},this.c.updateInterval));c||(this.Ua=g.setInterval(function(){d.i.X()},
this.c.renderInterval))}}function q(a){e.n("Creating Options");if("undefined"!==typeof a)for(var b in a)this[b]=a[b]}v.prototype.Hb=function(a){g.console.log("[voodoo] "+a)};v.prototype.n=function(a){this.Hb(a)};v.prototype.ac=function(a,b){this.n(a.pa+" "+b)};v.prototype.l=function(a){this.Hb("**ERROR** "+a);throw"Voodoo Exception: "+a;};v.prototype.d=function(a,b){a||this.l("Assert failed: "+b)};var e=new v;G.prototype.width=0;G.prototype.height=0;H.prototype.x=0;H.prototype.y=0;Z.prototype.disableStencils=
m;Z.prototype.drawStencils=m;Z.prototype.showFps=m;this.debug=new Z;N.prototype.convertCssColorToThreeJsColor=function(a){e.d(a,"cssColor undefined");e.d(3<=a.length,"cssColor too short");a=a.toLowerCase();return"#"==a[0]?this.Jb(a):0==a.indexOf("rgb(")?(a=a.substring(4,a.length-1).split(","),e.d(3==a.length,"Invalid rgb color"),this.Kb(a[0],a[1],a[2])):0==a.indexOf("rgba(")?(a=a.substring(5,a.length-1).split(","),e.d(4==a.length,"Invalid rgba color"),this.Kb(a[0],a[1],a[2])):0==a.indexOf("hsl(")?
(a=a.substring(4,a.length-1).split(","),e.d(3==a.length,"Invalid hsl color"),this.Ib(a[0],a[1],a[2])):0==a.indexOf("hsla(")?(a=a.substring(5,a.length-1).split(","),e.d(4==a.length,"Invalid hsla color"),this.Ib(a[0],a[1],a[2])):this.yc(a)};N.prototype.findAbsolutePosition=function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return{x:b,y:c}};N.prototype.Jb=function(a){return new THREE.Color(parseInt("0x"+a.substring(1),16))};N.prototype.Kb=function(a,
b,c){a=parseFloat(a)/255;b=parseFloat(b)/255;c=parseFloat(c)/255;e.d(0<=a,"r value < 0");e.d(1>=a,"r value > 1");e.d(0<=b,"g value < 0");e.d(1>=b,"g value > 1");e.d(0<=c,"b value < 0");e.d(1>=c,"b value > 1");return(new THREE.Color).setRGB(a,b,c)};N.prototype.Ib=function(a,b,c){a=parseFloat(a);b=parseFloat(b)/100;c=parseFloat(c)/100;e.d(0<=a,"h value < 0");e.d(360>a,"h value >= 360");e.d(0<=b,"s value < 0");e.d(1>=b,"s value > 1");e.d(0<=c,"l value < 0");e.d(1>=c,"l value > 1");b*=1-Math.abs(2*c-
1);var d=a/60,g=b*(1-Math.abs(parseInt(d,10)%2-1)),p=a=0,h=0;0<=d&&1>d?(a=b,p=g):1<=d&&2>d?(a=g,p=b):2<=d&&3>d?(p=b,h=g):3<=d&&4>d?(p=g,h=b):4<=d&&5>d?(a=g,h=b):5<=d&&6>d&&(a=b,h=g);c-=0.5*b;return(new THREE.Color).setRGB(a+c,p+c,h+c)};N.prototype.yc=function(a){e.d("undefined"!==typeof this.Gb[a],"Invalid color string");return this.Jb(this.Gb[a.toLowerCase()])};this.utility=new N;I.prototype.construct=function(){throw"Extendable::construct not implemented";};I.prototype.base={};I.extend=function(a){function b(){d.apply(this,
arguments)}function c(){}e.d("function"===typeof this,"Invalid Extendable.");var d=this;c.prototype=d.prototype;b.extend=d.extend;b.prototype=new c;var g=m;if("undefined"!==typeof a){g="function"===typeof a;e.d(!g||"undefined"!==typeof a.extend,"Extend must either be pased null, an object or another Extendable.");var p=g?a.prototype:a,h;for(h in p)b.prototype[h]=p[h]}b.prototype.constructor=b;p="undefined"===typeof d.ancestors?[]:d.ancestors.slice(0);this!==I&&p.push(d);g&&(p=p.concat(a.ancestors),
p.push(a));b.ancestors=p.slice(0);return b};this.Extendable=I;var F={Above:0,Below:1,BelowStencil:2,Seam:3,SeamStencil:4};x.prototype.sc=function(a){this.q.push(a)};x.prototype.Xc=function(a){a=this.q.indexOf(a);-1!=a&&this.q.splice(a,1)};x.prototype.Fb=l;x.prototype.e=l;x.prototype.ec=l;x.prototype.i=l;x.prototype.ic=l;x.prototype.za=l;x.prototype.q=l;L.prototype["delete"]=function(a,b,c){delete this.Ja(b,c)[a]};L.prototype.get=function(a,b,c){return this.Ja(b,c)[a]};L.prototype.has=function(a,b,
c){return this.Ja(b,c).hasOwnProperty(a)};L.prototype.set=function(a,b,c,d){this.Ja(c,d)[a]=b};L.prototype.Ja=function(a,b){var c,d;"undefined"===typeof a?(c=this.bc,d=this.cc):(c=a,d=b||"*");this.L.hasOwnProperty(d)||(this.L[d]={});this.L[d].hasOwnProperty(c)||(this.L[d][c]={});return this.L[d][c]};L.prototype.bc="";L.prototype.cc="";O.prototype.Lb=function(a){var b=new L(this.L);b.bc=a.name;b.cc=a.organization;return b};var ba=0,h=I.extend();h.prototype.cleanUp=function(){var a=this.base.cleanUp;
"function"===typeof a&&a()};h.prototype.construct=function(a){e.d(this.name,"Model type name cannot be undefined or null");e.d(this.viewType,"Model view type cannot be undefined or null");!this.viewType.prototype.above&&!this.viewType.prototype.below&&e.l("View must exist on at least one layer");this.stencilViewType=this.stencilViewType||this.viewType;this.dd();e.ac(this,"Constructing");if("undefined"===typeof g.voodoo.engine||g.voodoo.engine===l)g.voodoo.engine=new t(new q);this.h=new P;this.ed();
if("undefined"===typeof a||!a)a={};this.initialize(a);this.Cc();this.hd();this.setUpViews();g.voodoo.engine.rc(this)};h.prototype.destroy=function(){e.ac(this,"Destroying");this.k(new g.voodoo.Event("destroy",this));this.tearDownViews();g.voodoo.engine.Wc(this);this.A&&this.A.destroy&&this.A.destroy();this.va&&this.va.destroy&&this.va.destroy();this.cleanUp();this.h.C();this.va=this.A=this.h=l};h.prototype.dispatch=function(a){a.model=this;this.k(a);return this};h.prototype.initialize=function(a){var b=
this.base.initialize;"function"===typeof b&&b(a)};h.prototype.off=function(a,b){this.h.nb(a,b);return this};h.prototype.on=function(a,b){this.h.ob(a,b);"load"==a&&this.lb===this.mb&&b.call(this,new g.voodoo.Event("load",this));return this};h.prototype.setUpViews=function(){var a=this.base.setUpViews;"function"===typeof a&&a()};h.prototype.tearDownViews=function(){var a=this.base.tearDownViews;"function"===typeof a&&a()};h.prototype.update=function(a){var b=this.base.update;"function"===typeof b&&
b(a)};h.prototype.cache=l;h.prototype.stencilView=l;h.prototype.view=l;h.prototype.k=function(a){this.h.k(this,a)};h.prototype.Cc=function(){this.q=[];this.ma=[];this.mb=this.lb=0;for(var a=g.voodoo.engine.i.aa,b=this.stencilViewType==this.viewType,c=0;c<a.length;++c){var d=a[c];switch(d.ec){case F.Above:this.viewType.prototype.above&&this.q.push(new this.viewType(this,d));break;case F.Below:this.viewType.prototype.below&&this.q.push(new this.viewType(this,d));break;case F.Seam:this.viewType.prototype.above&&
this.q.push(new this.viewType(this,d));break;case F.BelowStencil:this.viewType.prototype.below&&(b?this.q.push(new this.viewType(this,d)):this.ma.push(new this.stencilViewType(this,d)));break;case F.SeamStencil:this.viewType.prototype.below&&(b?this.q.push(new this.viewType(this,d)):this.ma.push(new this.stencilViewType(this,d)))}}this.A=1<this.q.length?new V(this.q):this.q[0];this.va=1<this.ma.length?new V(this.ma):this.ma[0];this.mb=this.q.length+this.ma.length};h.prototype.dc=function(){this.lb++;
this.lb===this.mb&&this.k(new g.voodoo.Event("load",this))};h.prototype.dd=function(){this.pa="<"+ ++ba+",";"*"!==this.organization&&(this.pa+=this.organization+".");this.pa+=this.name+">"};h.prototype.ed=function(){this.L=g.voodoo.engine.jb.Lb(this);Object.defineProperty(this,"cache",{get:y("L"),set:function(){e.l("cache is read-only")},B:m})};h.prototype.hd=function(){Object.defineProperty(this,"view",{get:y("A"),set:function(){e.l("view is read-only")},B:m});Object.defineProperty(this,"stencilView",
{get:y("va"),set:function(){e.l("stencilView is read-only")},B:m})};h.prototype.name=l;h.prototype.organization="*";h.prototype.viewType=l;h.prototype.stencilViewType=l;h.extend=function(a){a=I.extend.call(this,a);var b=this.prototype.viewType,c=a.prototype.viewType;"undefined"!==typeof b&&(b!==l&&"undefined"!==typeof c&&c!==l&&b!=c)&&(a.prototype.viewType=b.extend(c));b=this.prototype.stencilViewType;c=a.prototype.stencilViewType;"undefined"!==typeof b&&(b!=l&&"undefined"!==typeof c&&c!=l&&b!=c)&&
(a.prototype.stencilViewType=b.extend(c));return a};this.Model=h;var n=I.extend();n.prototype.construct=function(a,b){e.d(a,"View model passed to initialize cannot be null");e.d(b,"View layer passed to initialize cannot be null");this.gd();this.u=a;this.W=b;this.j=this.W.ic.Mb(this);this.v=this.W.za.Nb(this);this.L=this.W.Fb.Lb(this.u);this.dirty();this.W.sc(this);this.qa=f;this.load();this.qa&&this.u.dc()};n.prototype.destroy=function(){this.unload();this.v.C();this.j.C();this.W.Xc(this);this.L=
this.W=this.j=this.v=this.u=l};n.prototype.dirty=function(){this.j.P=f};n.prototype.load=function(){var a=this.base.load;"function"===typeof a&&a()};n.prototype.unload=function(){var a=this.base.unload;"function"===typeof a&&a()};n.prototype.above=f;n.prototype.below=f;n.prototype.cache=l;n.prototype.camera=l;n.prototype.loaded=l;n.prototype.model=l;n.prototype.renderer=l;n.prototype.scene=l;n.prototype.triggers=l;n.prototype.gd=function(){Object.defineProperty(this,"cache",{get:y("L"),set:function(){e.l("cache is read-only")},
B:m});Object.defineProperty(this,"camera",{get:function(){return this.W.e},set:function(){e.l("camera is read-only")},B:m});Object.defineProperty(this,"loaded",{get:y("qa"),set:function(a){(this.qa=a)&&this.u.dc()},B:f});Object.defineProperty(this,"model",{get:y("u"),set:function(){e.l("model is read-only")},B:m});Object.defineProperty(this,"renderer",{get:function(){return this.W.i},set:function(){e.l("renderer is read-only")},B:m});Object.defineProperty(this,"scene",{get:y("j"),set:function(){e.l("scene is read-only")},
B:m});Object.defineProperty(this,"triggers",{get:y("v"),set:function(){e.l("triggers is read-only")},B:m})};n.extend=function(a){return I.extend.call(this,a)};this.View=n;X.prototype.C=function(){this.la&&(this.t.display="none",r.body.removeChild(this.t),this.la=m);g.clearInterval(this.Ec)};X.prototype.Fc=function(){this.gb++;g.voodoo.debug.showFps?(this.la||(this.t.display="block",r.body.appendChild(this.t),this.la=f),this.t.innerHTML="Frames/second: "+this.hb+", Renders/second: "+this.Yc):this.la&&
(this.t.display="none",r.body.removeChild(this.t),this.la=m)};X.prototype.X=function(){this.ub++};X.prototype.hb=0;M.prototype.fovY=0;M.prototype.position={};M.prototype.position.x=0;M.prototype.position.y=0;M.prototype.position.z=0;M.prototype.zNear=0;M.prototype.zFar=0;z.prototype.add=w();z.prototype.attach=w();z.prototype.detach=w();z.prototype.off=w();z.prototype.on=w();z.prototype.remove=w();z.prototype.objects=l;z.prototype.C=w();z.prototype.P=f;z.prototype.ra=l;z.prototype.ja=l;W.prototype.Mb=
function(){return l};var B={ThreeJs:0};this.Renderer=B;C.prototype.cb=w();C.prototype.C=w();C.prototype.X=w();C.prototype.vb=w();C.prototype.da=l;C.prototype.fa=l;C.prototype.ga=l;C.prototype.Va=l;C.prototype.Xa=l;C.prototype.Aa=l;Y.prototype.pc=function(a){var b=this.Lc++;this.Da[b]=a;this.kb++;a(this.Oa,this.Pa,this.Na,this.Ma,f,f);return b};Y.prototype.Uc=function(a){delete this.Da[a];this.kb--};Y.prototype.p=function(){var a=g.voodoo.utility.findAbsolutePosition(this.Ha),b=this.Ha.offsetWidth,
c=this.Ha.offsetHeight,d=a.x!==this.Oa||a.y!==this.Pa,e=b!==this.Na||c!==this.Ma;if(d||e){this.Oa=a.x;this.Pa=a.y;this.Na=b;this.Ma=c;for(var p in this.Da)this.Da[p].call(l,this.Oa,this.Pa,this.Na,this.Ma,d,e)}};Y.prototype.kb=0;$.prototype.Ya=function(a,b){e.d(a!==l&&"undefined"!==typeof a,"Element must be a valid HTML DOM element");e.d(b!==l&&"function"===typeof b,"Callback must be a valid function");var c,d;a.hasOwnProperty("VoodooTrackedElementId")?(d=a.VoodooTrackedElementId,c=this.xa[d]):(d=
a.VoodooTrackedElementId=this.Nc++,c=this.xa[d]=new Y(a));e.d("undefined"!==typeof c,"TrackedElement not found");var g=c.pc(b),p=this.Mc++;this.Ab[p]={md:d,ld:c,xc:g};return p};$.prototype.Vc=function(a){var b=this.Ab[a],c=b.ld,d=b.md,b=b.xc;delete this.Ab[a];c.Uc(b);0==c.kb&&(delete this.xa[d],delete c.Ha.VoodooTrackedElementId)};$.prototype.p=function(){for(var a in this.xa)this.xa[a].p()};P.prototype.C=function(){this.Z=l};P.prototype.k=function(a,b){var c=this.Z[b.type];if(c)for(var d=0;d<c.length;++d)c[d].call(a,
b)};P.prototype.nb=function(a,b){var c=this.Z[a];c&&c.lc(b)&&c.splice(c.lc(b),1)};P.prototype.ob=function(a,b){this.Z[a]||(this.Z[a]=[]);-1==this.Z[a].indexOf(b)&&this.Z[a].push(b)};Q.prototype.Ka=function(a){return a!=l&&this.u==a.u&&this.Za==a.Za};Q.prototype.u=l;Q.prototype.ba=l;Q.prototype.f=l;Q.prototype.Za=-1;Q.prototype.A=l;this.s=function(a,b,c){this.type=a;this.model=b;this.triggerId="undefined"===typeof c?-1:c};this.s.prototype.Jc=function(a,b,c,d,e,g){this.client.x=a;this.client.y=b;this.hit.x=
c;this.hit.y=d;this.hit.z=e;this.button=g||0};this.s.prototype.button=0;this.s.prototype.client={};this.s.prototype.client.x=Number.MAX_VALUE;this.s.prototype.client.y=Number.MAX_VALUE;this.s.prototype.hit={};this.s.prototype.hit.x=Number.MAX_VALUE;this.s.prototype.hit.y=Number.MAX_VALUE;this.s.prototype.hit.z=Number.MAX_VALUE;this.s.prototype.model=l;this.s.prototype.object=l;this.s.prototype.size={};this.s.prototype.size.x=Number.MAX_VALUE;this.s.prototype.size.y=Number.MAX_VALUE;this.s.prototype.type=
l;this.s.prototype.triggerId=-1;this.Event=this.s;U.prototype.add=w();U.prototype.cursor=function(a){this.Ob=a};U.prototype.remove=w();U.prototype.C=w();U.prototype.Ob="auto";ca.prototype.Nb=function(){return l};ca.prototype.v=l;da.prototype.Sa=function(){return l};da.prototype.wb=w();D.prototype.qc=function(){var a=this;r.addEventListener("mousemove",function(b){a.Pc(b)},m);r.addEventListener("mousedown",function(b){a.Oc(b)},m);r.addEventListener("mouseup",function(b){a.Qc(b)},m)};D.prototype.C=
function(){this.Sb();this.a=l};D.prototype.T=function(a,b,c,d){e.d(b,"trigger must not be null");a=new g.voodoo.Event(a,b.u,b.Za);a.Jc(this.eb,this.fb,this.Xb,this.Yb,this.Zb,c);(d||b).u.k(a)};D.prototype.Sb=function(){this.m=l;this.U=[l,l,l];this.$=[l,l,l];this.sd=m;this.pb=[m,m,m];this.Ra=m;this.Zb=this.Yb=this.Xb=this.fb=this.eb=0;this.Wb=[l,l,l];this.Ub=[0,0,0];this.Vb=[0,0,0]};D.prototype.Oc=function(a){if(this.m!=l){a.preventDefault();var b=this.$[a.button],c=new Date-this.Wb[a.button];this.U[a.button]=
this.m;this.T("mousedown",this.m,a.button);this.U[a.button].Ka(b)&&(this.Ub[a.button]==a.clientX&&this.Vb[a.button]==a.clientY&&c<=this.a.c.Dc)&&(this.pb[a.button]=f)}};D.prototype.Pc=function(a){this.m!=l&&a.preventDefault();this.eb=a.clientX;this.fb=a.clientY;this.Ra=f;this.a.c.realtime&&this.p()};D.prototype.Qc=function(a){if(this.m!=l){a.preventDefault();this.T("mouseup",this.m,a.button);var b=this.U[a.button],c=this.$[a.button];b&&this.m!=b&&this.T("mouseup",this.m,a.button,b);this.m.Ka(b)&&
(this.T("click",this.U[a.button],a.button),this.pb[a.button]&&b.Ka(c)?(this.$[a.button]=l,this.pb[a.button]=m,this.T("dblclick",b,a.button)):(this.$[a.button]=b,this.Wb[a.button]=new Date,this.Ub[a.button]=a.clientX,this.Vb[a.button]=a.clientY))}this.U[a.button]=l};D.prototype.Sa=function(){var a=this.a.ua.Sa();this.Xb=a.Gc;this.Yb=a.Hc;this.Zb=a.Ic;return a.ya};D.prototype.p=function(){this.Ra&&this.a.ua.wb(new H(this.eb,this.fb));var a=this.Sa();a!=l?(this.Ra&&this.T("mousemove",a),a.Ka(this.m)||
(this.m!=l&&this.T("mouseout",this.m),this.T("mouseover",a)),this.a.i.cb(f)):(this.m!=l&&this.T("mouseout",this.m),this.a.i.cb(m));this.m=a;this.Ra=m;this.m!=l?this.a.i.vb(this.m.f.Ob):this.a.i.vb("auto")};u.prototype=new M;u.prototype.constructor=u.constructor;u.prototype.Bc=function(){Object.defineProperty(this,"fovY",{get:y("Ia"),set:function(){e.l("fovy is read-only")},B:m});Object.defineProperty(this,"position",{get:function(){return{x:this.e.position.x,y:this.e.position.y,z:this.e.position.z}},
set:function(){e.l("position is read-only")},B:m});Object.defineProperty(this,"zNear",{get:y("F"),set:function(){e.l("zNear is read-only")},B:m});Object.defineProperty(this,"zFar",{get:y("I"),set:function(){e.l("zFar is read-only")},B:m})};u.prototype.Kc=function(){this.ta=this.qb=this.rb=f;this.e.up.x=0;this.e.up.y=-1;this.e.up.z=0;this.ka();this.p();var a=this;g.addEventListener("scroll",function(){a.sa()},m);g.addEventListener("resize",function(){a.ka()},m);this.R=f};u.prototype.sa=function(){this.rb=
f};u.prototype.ka=function(){this.qb=f;this.sa()};u.prototype.ca=function(a,b){this.F=a;this.I=b;this.e.projectionMatrix.makePerspective(this.Ia,this.Cb,this.F,this.I);this.ta=f;this.p()};u.prototype.p=function(){if(this.qb){var a=parseInt(this.Ea.style.width,10),b=parseInt(this.Ea.style.height,10);this.Cb=a/b;a=Math.tan(this.Ia/360*Math.PI);this.rd=b/2/a;this.e.projectionMatrix.makePerspective(this.Ia,this.Cb,this.F,this.I);this.e.position.z=this.rd;this.e.scale.x=-1;this.qb=m;this.ta=this.R=f}this.rb&&
(a=parseInt(this.Ea.style.width,10),b=parseInt(this.Ea.style.height,10),this.e.position.x=a/2+g.pageXOffset,this.e.position.y=b/2+g.pageYOffset,this.e.lookAt(new THREE.Vector3(this.e.position.x,this.e.position.y,0)),this.rb=m,this.ta=this.R=f);this.ta&&(this.e.updateMatrixWorld(f),b=new THREE.Matrix4,b.getInverse(this.e.matrixWorld),this.ib.setFromMatrix((new THREE.Matrix4).multiplyMatrices(this.e.projectionMatrix,b)),this.ta=m)};u.prototype.e=l;u.prototype.ib=l;u.prototype.R=m;J.prototype=new da;
J.prototype.constructor=J.constructor;J.prototype.Pb=function(a,b){for(var c=this.i.da.za.v,d=0;d<c.length;++d){var e=c[d],g=e.u,h=this.nc.intersectObject(e.ba,f);if(!(0>=h.length)&&!(0>=h[0].distance||h[0].distance>=a.Ga))if(!this.a.c.belowLayer||!(0>h[0].point.z&&e.A.below&&this.a.c.stencils&&g.viewType!=g.stencilViewType&&-1===b.indexOf(g)))a.Ga=h[0].distance,a.ya=e,a.tb=h[0].point}return a};J.prototype.Qb=function(a,b){for(var c=this.i.fa.za.v,d=0;d<c.length;++d){var e=c[d],g=e.u,h=e.ba;if(!this.a.c.aboveLayer||
!g.view.above)if(h=this.Db.intersectObject(h,f),!(0>=h.length)&&!(0<=h[0].point.z)&&!(0>=h[0].distance||h[0].distance>=a.Ga))if(!this.a.c.stencils||!(g.viewType!=g.stencilViewType&&-1===b.indexOf(g)))a.Ga=h[0].distance,a.ya=e,a.tb=h[0].point}return a};J.prototype.Rb=function(){for(var a=[],b=this.i.ga.za.v,c=0;c<b.length;++c){var d=b[c],e=d.ba,g=d.u;g.viewType!==g.stencilViewType&&d.A.below&&-1===b.indexOf(g)&&0<this.Db.intersectObject(e,f).length&&a.push(g)}return a};J.prototype.Sa=function(){var a=
{Ga:Number.MAX_VALUE,ya:l,tb:l};if(this.a.c.belowLayer&&this.a.c.aboveLayer)var b=this.a.c.stencils?this.Rb():[],a=this.Pb(a,b),a=this.Qb(a,b);else this.a.c.aboveLayer?a=this.Pb(a,[]):this.a.c.belowLayer&&(b=this.Rb(),a=this.Qb(a,b));b=a.tb;return{ya:a.ya,Gc:b?b.x:Number.MAX_VALUE,Hc:b?b.y:Number.MAX_VALUE,Ic:b?b.z:Number.MAX_VALUE}};J.prototype.wb=function(a){var b=2*(a.x/this.i.Aa.width)-1;a=2*-(a.y/this.i.Aa.height)+1;if(this.a.c.aboveLayer){var c=this.i.da.e.e;this.Ba=new THREE.Vector3(b,a,1);
this.gc.unprojectVector(this.Ba,c);this.Ba=this.Ba.sub(c.position).normalize();this.nc=new THREE.Raycaster(c.position,this.Ba)}this.a.c.belowLayer&&(c=this.i.fa.e.e,this.Ca=new THREE.Vector3(b,a,1),this.gc.unprojectVector(this.Ca,c),this.Ca=this.Ca.sub(c.position).normalize(),this.Db=new THREE.Raycaster(c.position,this.Ca))};A.prototype=new z;A.prototype.constructor=A.constructor;A.prototype.add=function(a){a.addedToVoodooTriggers?a.visible=f:this.f.add(a);a.addedToVoodooScene=f;this.ra.push(a);this.Tb(a)&&
this.ja.push(a);var b=new g.voodoo.Event("add");b.object=a;this.h.k(this.A,b)};A.prototype.attach=function(a,b,c){"undefined"===typeof b&&(b=f);"undefined"===typeof c&&(c=f);this.wa!==l&&this.detach();var d=this;a&&"undefined"!==typeof a&&(this.wa=b?c?this.S.Ya(a,function(b,c,e,h,k,n){d.f.position.x=b+e/2;d.f.position.y=c+h/2;d.f.scale.x=d.f.scale.y=1;d.f.updateMatrixWorld(f);d.P=f;k&&(k=new g.voodoo.Event("move"),k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k));n&&(k=new g.voodoo.Event("resize"),
k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k))}):this.S.Ya(a,function(b,c,e,h,k,n){d.f.position.x=b+e/2;d.f.position.y=c+h/2;d.f.scale.x=e;d.f.scale.y=h;d.f.updateMatrixWorld(f);d.P=f;k&&(k=new g.voodoo.Event("move"),k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k));n&&(k=new g.voodoo.Event("resize"),k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k))}):c?this.S.Ya(a,function(b,c,e,h,k,n){d.f.position.x=b;d.f.position.y=c;d.f.scale.x=
d.f.scale.y=1;d.f.updateMatrixWorld(f);d.P=f;k&&(k=new g.voodoo.Event("move"),k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k));n&&(k=new g.voodoo.Event("resize"),k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k))}):this.S.Ya(a,function(b,c,e,h,k,n){d.f.position.x=b;d.f.position.y=c;d.f.scale.x=e;d.f.scale.y=h;d.f.updateMatrixWorld(f);d.P=f;k&&(k=new g.voodoo.Event("move"),k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k));n&&(k=new g.voodoo.Event("resize"),
k.object=a,k.client.x=b,k.client.y=c,k.size.x=e,k.size.y=h,d.h.k(l,k))}),b=new g.voodoo.Event("attach"),b.object=a,this.h.k(this.A,b))};A.prototype.detach=function(){var a=new g.voodoo.Event("detach");this.h.k(l,a);this.S.Vc(this.wa);this.wa=l;this.f.position.x=this.f.position.y=0;this.f.scale.x=this.f.scale.y=1;this.f.updateMatrixWorld(f)};A.prototype.off=function(a,b){this.h.nb(a,b)};A.prototype.on=function(a,b){this.h.ob(a,b)};A.prototype.remove=function(a){var b=new g.voodoo.Event("remove");b.object=
a;this.h.k(this.A,b);a.addedToVoodooTriggers?a.visible=m:this.f.remove(a);a.addedToVoodooScene=m;b=this.ra.indexOf(a);-1!=b&&this.ra.splice(b,1);this.Tb(a)&&(b=this.ja.indexOf(a),-1!=b&&this.ja.splice(b,1))};A.prototype.C=function(){this.j.remove(this.f);this.wa!==l&&this.detach();this.h.C();this.f=this.A=this.j=this.h=l};A.prototype.Tb=function(a){return a instanceof THREE.Mesh||a instanceof THREE.MorphAnimMesh||a instanceof THREE.SkinnedMesh||a instanceof THREE.Line};E.prototype=new W;E.prototype.constructor=
E.constructor;E.prototype.Mb=function(a){return new A(this.j,a)};E.prototype.j=l;R.prototype=new U;R.prototype.constructor=R.constructor;R.prototype.add=function(a,b){e.d(a,"Object must be valid");for(var c=new Q(this.A,a,this,b),d=0;d<this.v.length;++d)this.v[d].ba==c.ba&&e.l("Trigger already exists");this.v.push(c);a.addedToVoodooScene||(a.visible=m,this.j.add(a));a.addedToVoodooTriggers=f};R.prototype.remove=function(a){for(var b=0;b<this.v.length;++b)this.v[b].ba==a&&this.v.splice(b,1);a.addedToVoodooScene&&
this.j.remove(a);a.addedToVoodooTriggers=m};R.prototype.C=function(){this.A=this.j=this.v=l};K.prototype=new ca;K.prototype.constructor=K.constructor;K.prototype.Nb=function(a){return new R(this.v,a.scene.j,a)};s.prototype=new C;s.prototype.constructor=s.constructor;s.prototype.cb=function(a){a?(this.a.c.aboveLayer&&(this.J.style.pointerEvents="auto"),this.a.c.belowLayer&&(this.G.style.pointerEvents="auto"),this.a.c.seamLayer&&(this.H.style.pointerEvents="auto")):(this.a.c.aboveLayer&&(this.J.style.pointerEvents=
"none"),this.a.c.belowLayer&&(this.G.style.pointerEvents="none"),this.a.c.seamLayer&&(this.H.style.pointerEvents="none"))};s.prototype.na=function(a){if(a&&"undefined"!==typeof a)for(var b in a.q)a.q[b].scene.P=m};s.prototype.zc=function(){e.n("Creating WebGL renderers");this.bb=1;var a={antialias:this.a.c.antialias,alpha:f};this.a.c.aboveLayer&&(this.Y=new THREE.WebGLRenderer(a),this.J=this.Y.domElement,this.xb(this.Y),this.J.style.zIndex=this.a.c.aboveZIndex);this.a.c.belowLayer&&(this.o=new THREE.WebGLRenderer(a),
this.G=this.o.domElement,this.xb(this.o),this.G.style.zIndex=this.a.c.belowZIndex);this.a.c.aboveLayer&&this.Y.context.getContextAttributes().antialias||this.a.c.belowLayer&&this.o.context.getContextAttributes().antialias||(this.a.c.antialias=m,this.a.c.seamLayer=m);if(!this.a.c.aboveLayer||!this.a.c.belowLayer)this.a.c.seamLayer=m;this.a.c.seamLayer&&(this.M=new THREE.WebGLRenderer({antialias:m,alpha:f}),this.H=this.M.domElement,this.xb(this.M),this.H.style.zIndex=this.a.c.seamZIndex);this.ka(l);
this.sa(l)};s.prototype.Ac=function(){e.n("Creating layers");var a=this.a.c.renderer;this.a.c.aboveLayer&&(this.O=new u(this.J,this.a.c.fovY,this.a.c.F,this.a.c.I),this.Bb=new E,this.oc=new K,this.mc=new O,this.da=new x(F.Above,a,this.O,this.Bb,this.oc,this.mc),this.aa.push(this.da));this.a.c.belowLayer&&(this.K=new u(this.G,this.a.c.fovY,this.a.c.F,this.a.c.I),this.Eb=new E,this.wc=new K,this.tc=new O,this.fa=new x(F.Below,a,this.K,this.Eb,this.wc,this.tc),this.aa.push(this.fa),this.a.c.stencils&&
(this.N=new u(this.G,this.a.c.fovY,this.a.c.F,this.a.c.I),this.ab=new E,this.vc=new K,this.uc=new O,this.ga=new x(F.BelowStencil,a,this.N,this.ab,this.vc,this.uc),this.aa.push(this.ga)));this.a.c.seamLayer&&(this.D=new u(this.H,this.a.c.fovY,this.a.c.F,this.a.c.I),this.Wa=new E,this.cd=new K,this.Zc=new O,this.Va=new x(F.Seam,a,this.D,this.Wa,this.cd,this.Zc),this.aa.push(this.Va),this.a.c.stencils&&("undefined"===typeof this.N&&(this.N=new u(this.H,this.a.c.fovY,this.a.c.F,this.a.c.I)),this.jc=new E,
this.bd=new K,this.ad=new O,this.Xa=new x(F.SeamStencil,a,this.N,this.jc,this.bd,this.ad),this.aa.push(this.Xa)));this.sb=m;this.kc();var b=this;g.addEventListener("resize",function(){b.sb=f},m)};s.prototype.C=function(){this.a.c.aboveLayer&&r.body.removeChild(this.J);this.a.c.belowLayer&&r.body.removeChild(this.G);this.a.c.seamLayer&&r.body.removeChild(this.H);this.oa.C()};s.prototype.ha=function(a){if(this.P)return f;if(!a||"undefined"===typeof a)return m;var b=a.e.ib,c;for(c in a.q){var d=a.q[c],
e=d.scene;if(d.qa&&e.P){if(e.ja.length!==e.ra.length)return f;var d=e.ja,g;for(g in d)if(e=d[g],e.geometry&&"undefined"!==typeof e.geometry&&(e.updateMatrixWorld(f),b.intersectsObject(e)))return f}}return m};s.prototype.ka=function(a){this.od();var b=this.Aa.width,c=this.Aa.height,d=b+"px",e=c+"px",h=g.devicePixelRatio||1,b=b*h*this.bb,c=c*h*this.bb;this.a.c.aboveLayer&&(this.Y.setViewport(0,0,b,c),this.J.style.width=d,this.J.style.height=e,this.J.width=b,this.J.height=c);this.a.c.belowLayer&&(this.o.setViewport(0,
0,b,c),this.G.style.width=d,this.G.style.height=e,this.G.width=b,this.G.height=c);this.a.c.seamLayer&&(this.M.setViewport(0,0,b,c),this.H.style.width=d,this.H.style.height=e,this.H.width=b,this.H.height=c);r.body.style.display="none";r.body.style.display="block";this.P=f;this.a.c.realtime&&a&&this.X()};s.prototype.sa=function(a){this.yb=g.pageXOffset+"px";this.zb=g.pageYOffset+"px";this.P=f;this.a.c.realtime&&a&&this.X()};s.prototype.Tc=function(){e.n("Registering for window events");var a=this;g.addEventListener("scroll",
function(b){a.sa.call(a,b)},m);g.addEventListener("resize",function(b){a.ka.call(a,b)},m)};s.prototype.X=function(){var a=m;this.nd();this.oa.Fc();this.a.c.performanceScaling&&!this.fc&&(this.oa.hb>this.a.c.Rc||0==this.a.V?this.$b=new Date:(new Date-this.$b)/1E3>this.a.c.Sc&&(e.n("Enabling performance scaling"),this.bb=0.5,this.fc=f,this.ka(l)));if(g.voodoo.debug.drawStencils)this.a.c.stencils?this.a.c.belowLayer&&this.ha(this.ga)&&(this.o.context.disable(this.o.context.STENCIL_TEST),this.o.autoClear=
f,this.o.render(this.ab.j,this.K.e),a=f):this.o.clear(),this.Y.clear(),this.M.clear();else{if(this.a.c.belowLayer&&(this.ha(this.fa)||this.ha(this.ga)))!this.a.c.stencils||g.voodoo.debug.disableStencils?(this.o.context.disable(this.o.context.STENCIL_TEST),this.o.autoClear=f):(a=this.o.context,a.enable(a.STENCIL_TEST),a.clearStencil(0),a.stencilOp(a.REPLACE,a.REPLACE,a.REPLACE),a.stencilFunc(a.NEVER,1,4294967295),this.o.autoClear=m,this.o.clear(),this.o.render(this.ab.j,this.N.e),a.stencilOp(a.KEEP,
a.KEEP,a.KEEP),a.stencilFunc(a.EQUAL,1,4294967295)),this.o.render(this.Eb.j,this.K.e),a=f;this.a.c.aboveLayer&&this.ha(this.da)&&(this.Y.render(this.Bb.j,this.O.e),a=f);if(this.a.c.seamLayer&&(this.ha(this.Va)||this.ha(this.Xa))){var b=this.a.c.$c,c=this.D.position.z,a=this.M.context;a.enable(a.STENCIL_TEST);this.M.autoClear=m;this.M.clear();!this.a.c.stencils||g.voodoo.debug.disableStencils?a.clearStencil(0):(a.clearStencil(1),a.stencilOp(a.REPLACE,a.REPLACE,a.REPLACE),a.stencilFunc(a.NEVER,0,4294967295),
this.M.render(this.jc.j,this.N.e),this.D.ca(c-b,c),this.M.render(this.Wa.j,this.D.e));a.stencilOp(a.REPLACE,a.REPLACE,a.REPLACE);a.stencilFunc(a.NEVER,1,4294967295);this.D.ca(this.a.c.F,c-b);this.M.render(this.Wa.j,this.D.e);a.stencilOp(a.KEEP,a.KEEP,a.KEEP);a.stencilFunc(a.NOTEQUAL,1,4294967295);this.D.ca(c-b,c+b);this.M.render(this.Wa.j,this.D.e);a=f}}this.a.c.aboveLayer&&(this.Y.context.finish(),this.J.style.left=this.yb,this.J.style.top=this.zb);this.a.c.belowLayer&&(this.o.context.finish(),this.G.style.left=
this.yb,this.G.style.top=this.zb);this.a.c.seamLayer&&(this.M.context.finish(),this.H.style.left=this.yb,this.H.style.top=this.zb);this.P=m;this.na(this.da);this.na(this.fa);this.na(this.ga);this.na(this.Va);this.na(this.Xa);a&&this.oa&&this.oa.X()};s.prototype.vb=function(a){this.a.c.aboveLayer&&(this.J.style.cursor=a);this.a.c.belowLayer&&(this.G.style.cursor=a);this.a.c.seamLayer&&(this.H.style.cursor=a)};s.prototype.xb=function(a){var b=a.domElement,c=b.style;a.setFaceCulling(THREE.CullFaceFront,
THREE.FrontFaceDirectionCCW);c.position="absolute";c.pointerEvents="none";r.body.appendChild(b)};s.prototype.nd=function(){"undefined"!==typeof this.O&&this.O.p();"undefined"!==typeof this.K&&this.K.p();"undefined"!==typeof this.D&&this.D.p();"undefined"!==typeof this.N&&this.N.p();this.sb&&(this.kc(),this.sb=m);if("undefined"!==typeof this.O&&this.O.R||"undefined"!==typeof this.K&&this.K.R||"undefined"!==typeof this.D&&this.D.R||"undefined"!==typeof this.N&&this.N.R){for(var a=this.a.Q,b=new g.voodoo.Event("cameramove"),
c=0;c<a.length;++c)a[c].k(b);"undefined"!==typeof this.O&&(this.O.R=m);"undefined"!==typeof this.K&&(this.K.R=m);"undefined"!==typeof this.D&&(this.D.R=m);"undefined"!==typeof this.N&&(this.N.R=m)}};s.prototype.kc=function(){if(this.a.c.belowLayer)if(this.a.c.aboveLayer){var a=this.K.position.z;this.K.ca(a-0.5,this.a.c.I)}else this.K.ca(this.a.c.F,this.a.c.I);this.a.c.aboveLayer&&(this.a.c.belowLayer?(a=this.O.position.z,this.O.ca(this.a.c.F,a)):this.O.ca(this.a.c.F,this.a.c.I))};s.prototype.od=function(){var a=
r.createElement("div");a.style.cssText="position: fixed; top: 0; left: 0; bottom: 0; right: 0;";r.documentElement.insertBefore(a,r.documentElement.firstChild);this.Aa=new G(a.offsetWidth,a.offsetHeight);r.documentElement.removeChild(a)};s.prototype.pd=function(){e.n("Validating and preparing webpage for use");e.d(r.body,"document.body is undefined");r.body.style.width="100%";r.body.style.height="100%";r.body.style.margin="0px"};s.prototype.aa=l;t.prototype.destroy=function(){e.n("Destroying Engine");
this.h.k(l,new g.voodoo.Event("destroy"));-1!==this.$a&&g.clearInterval(this.$a);-1!==this.Ua&&g.clearInterval(this.Ua);for(-1!==this.Ta&&g.cancelAnimationFrame(this.Ta);0<this.Q.length;)this.Q[0].destroy();this.Q=l;this.i.C();this.Qa.C();this.h.C();"undefined"!==typeof g.voodoo.engine&&delete g.voodoo.engine;this.Q=this.h=this.Qa=this.i=l;this.Ta=this.Ua=this.$a=-1;this.S=this.jb=this.c=l};t.prototype.frame=function(){this.p();this.i.X()};t.prototype.off=function(a,b){this.h.nb(a,b)};t.prototype.on=
function(a,b){this.h.ob(a,b)};t.prototype.models=l;t.prototype.rc=function(a){this.Q.push(a);this.h.k(l,new g.voodoo.Event("addmodel",a))};t.prototype.Wc=function(a){this.Q.splice(this.Q.indexOf(a),1);this.h.k(l,new g.voodoo.Event("removemodel",a))};t.prototype.hc=function(a,b){var c=this;this.Ta=requestAnimationFrame(function(){c.hc(a,b)});a&&this.p();b&&this.i.X()};t.prototype.fd=function(){e.n("Starting timers");var a=this;this.La=this.V=0;g.addEventListener("focus",function(){a.V=0;setTimeout(function(){a.V=
Date.now()},a.c.jd)},m);g.addEventListener("blur",function(){a.V=0},m);setTimeout(function(){if(!r.hasFocus||r.hasFocus())a.V=Date.now()},a.c.kd)};t.prototype.p=function(){var a=0,b=Date.now();0!=this.V&&(a=(b-this.V)/1E3,this.V=b);a>2*this.La?(b=this.La,this.La=a,a=b):this.La=a;this.S.p();for(var b=this.Q,c=0;c<b.length;++c)b[c].update(a);this.Qa.p()};t.prototype.qd=function(){!this.c.aboveLayer&&!this.c.belowLayer&&e.l("At least one layer must be enabled")};t.prototype.Qa=l;t.prototype.jb=l;t.prototype.c=
l;t.prototype.ua=l;t.prototype.i=l;this.engine=t.prototype.S=l;this.Engine=t;this.version=l;q.prototype.aboveLayer=f;q.prototype.aboveZIndex=9999;q.prototype.antialias=f;q.prototype.belowLayer=f;q.prototype.belowZIndex=-1;q.prototype.Dc=500;q.prototype.fovY=30;q.prototype.frameLoop=f;q.prototype.performanceScaling=f;q.prototype.Rc=45;q.prototype.Sc=3;q.prototype.realtime=f;q.prototype.renderer=B.ThreeJs;q.prototype.renderInterval=0;q.prototype.$c=10;q.prototype.seamLayer=f;q.prototype.seamZIndex=
1E4;q.prototype.standardLighting=f;q.prototype.stencils=f;q.prototype.jd=350;q.prototype.kd=1E3;q.prototype.updateInterval=0;q.prototype.I=1E4;q.prototype.F=0.1;this.Options=q;var S=n.extend();S.prototype.createLight=function(){throw"createLight_() undefined.";};S.prototype.load=function(){e.d(this.renderer==B.ThreeJs,"Only ThreeJs is supported");this.ia=this.createLight();this.scene.add(this.ia)};S.prototype.unload=function(){e.d(this.renderer==B.ThreeJs,"Only ThreeJs is supported");this.scene.remove(this.ia)};
S.prototype.setColor=function(a){e.d(this.renderer==B.ThreeJs,"Only ThreeJs is supported");a=g.voodoo.utility.convertCssColorToThreeJsColor(a);this.ia.color.copy(a)};h=h.extend();h.prototype.initialize=function(a){this.Fa="undefined"!==typeof a.color?a.color:l;Object.defineProperty(this,"color",{get:y("Fa"),set:function(a){this.view.setColor(a);this.Fa=a},B:f})};h.prototype.setUpViews=function(){this.color=this.Fa?this.Fa:"black"};h.prototype.color=l;h.prototype.stencilViewType=n.extend();n=S.extend();
n.prototype.createLight=function(){e.d(this.renderer==B.ThreeJs,"Only ThreeJs is supported");return new THREE.AmbientLight};var ea=h.extend();ea.prototype.name="AmbientLight";ea.prototype.viewType=n;n=S.extend();n.prototype.createLight=function(){e.d(this.renderer==B.ThreeJs,"Only ThreeJs is supported");return new THREE.PointLight};n.prototype.load=function(){S.prototype.load.apply(this);this.updatePosition()};n.prototype.updatePosition=function(){e.d(this.renderer==B.ThreeJs,"Only ThreeJs is supported");
this.ia.position.x=this.camera.position.x;this.ia.position.y=this.camera.position.y;this.ia.position.z=this.camera.position.z};var aa=h.extend();aa.prototype.name="CameraLight";aa.prototype.viewType=n;aa.prototype.setUpViews=function(){this.on("cameramove",function(){this.view.updatePosition()})}}for(var v=["voodoo"],G=g,H=0;H<v.length-1;++H)G=G[v[H]];if("undefined"===typeof G[v[v.length-1]])G[v[v.length-1]]=new W;else{var H=G[v[v.length-1]],ba=new W,V;for(V in ba)H[V]=ba[V]}G[v[v.length-1]].version=
"0.8.8"})(window,document,void 0);
